docs/styles.css

Using max-width instead of fixed width so it won't break on smaller screens

Simple responsive

---

tty/src/lib.rs

remove dead code

---

README.md
config/src/lib.rs

Ref: https://github.com/raphamorim/rio/discussions/6#discussioncomment-5431603

config: use XDG base directory

---

colors/src/lib.rs
rio/src/screen/state.rs

#52
I used `ColorBuilder` as you suggested.

fix to render specific 24bit colors

---

rio/src/screen/state.rs

fix rendering tab and hidden chars by replacing to space

---

sugarloaf/src/font/mod.rs

Font style for custom fonts

---

docs/install/index.md

Please feel free to provide any feedback. Mostyle a WIP for now, but I think it's looking good. 
I had to use "bash" to make the code block look good. It didn't work quite right with "toml" producing weird syntax highlighting.

Update Windows installation docs

---

config/src/defaults.rs
docs/docs/index.md

set macOS shell default empty, get SHELL env

---

CHANGELOG.md
Cargo.lock
Cargo.toml
rio/Cargo.toml

Cutdown tokio to minimal setup. Cuts down binary from 24mb to 16mb

feat: cutdown tokio features

---

CHANGELOG.md
docs/_posts/2023-07-19-release-0.0.11.md
docs/_posts/2023-08-02-release-0.0.15.md
docs/docs/index.md

Fix some typos

---

sugarloaf/src/context/mod.rs

Currently on Nvidia GPUs Rgba16Float texture format causes driver to enable HDR. Reason for this is currently output color space is poorly defined in wgpu and anything other than Srgb texture formats can cause undeterministic output color space selection which also causes colors to mismatch. Optionally we can whitelist only the Srgb texture formats for now until output color space selection lands in wgpu. Temporarily fixes #205

hack for the undefined output color space

---

docs/install/index.md

Thanks @androw for the aport
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/51369

docs: add alpine linux package

---

CHANGELOG.md
docs/docs/configuration-file.md
rio-config/src/defaults.rs
rio-config/src/window.rs

- Rename Regular window mode to Windowed
- Document Regular -> Windowed rename
- Add Regular -> Windowed rename to changelog

Rename Regular window mode to Windowed

---

docs/install/index.md

https://build.opensuse.org/package/show/openSUSE%3AFactory/rioterm

docs: add opensuse linux package

---

docs/docs/configuration-file.md

Update configuration-file.md: fix broken link

---

rio/src/event/mod.rs
rio/src/screen/context.rs
rio/src/screen/mod.rs
rio/src/sequencer.rs

Fix #229 
Add ToggleFullscreen Action. Bind key: `Command + Control + F`
Fn does not support on winit, also have some problems with Apple Fn key with external keyboard

Add ToggleFullscreen Action #229

---

docs/blog/2023-07-07-release-0.0.7.md
docs/blog/2023-07-17-release-0.0.9.md
docs/blog/2023-07-19-release-0.0.11.md
docs/blog/2023-08-02-release-0.0.15.md
docs/blog/2023-08-29-release-0.0.17.md
docs/blog/2023-09-19-release-0.0.19.md
docs/docs/documentation/key-bindings.md
docs/docs/features/index.md
docs/docs/install/freebsd.md
docs/docs/install/linux.md
docs/docs/install/macos.md
docs/docs/install/windows.md

1. Fix some image link issues.
2. Improve the formatting of tables, code blocks, and lists.

docs: markdown

---

rio-config/src/defaults.rs
rio-config/src/lib.rs
rio/src/screen/mod.rs
rio/src/screen/mouse.rs

added scroll_modifier to Config and set default as 2.0 
related to: #278

feat: added scroll_modifier to Config with default 2.0

---

docs/docs/install/linux.md

Add link to Void Linux package in install docs

---

docs/docusaurus.config.js
docs/jsconfig.json
docs/package-lock.json
docs/package.json
docs/src/pages/index.js
docs/src/pages/markdown-page.md

- Add `jsconfig.json` to get the typing system working well
- Fix duplicate title
e.g. "Documentation | Meet Rio | Rio Terminal" to "Documentation | Rio Terminal" and "Meet Rio | Rio Terminal | Meet Rio | Rio Terminal" to "Meet Rio | Rio Terminal"
- Remove unused page file

Bit improve docs

---

docs/docusaurus.config.js
docs/src/css/custom.css

Add web font to facilitate design ease and provide a consistent experience to users.
For now, I have set it to [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans). Do you have a preferred font?

Add web font

---

docs/blog/2023-08-02-release-0.0.15.mdx
docs/docs/documentation/navigation.md
docs/docs/features/color-automation-for-navigation.md
docs/docs/install/build-from-source.md
docs/docs/install/index.md
docs/src/pages/index.module.css

- Fix incorrectly assigned colors.
- Fix an issue in development mode.

Fix some issues for docs

---

docs/blog/2023-05-31-release-0.0.5.md
docs/blog/2023-07-10-release-0.0.8.mdx
docs/blog/2023-07-17-release-0.0.9.md
docs/blog/2023-08-02-release-0.0.15.mdx
docs/blog/2023-08-29-release-0.0.17.md
docs/blog/2023-09-19-release-0.0.19.md
docs/docs/features/adaptive-theme.md
docs/docs/features/hyperlinks.md
docs/docs/features/index.md
docs/docs/features/kitty-keyboard-protocol.md
docs/docs/features/navigation.md
docs/docs/features/spawn-or-fork.md
docs/docs/features/vi-mode.md
docs/docs/install/windows.md
docs/docusaurus.config.js
docs/i18n/ko/code.json
docs/i18n/ko/docusaurus-theme-classic/navbar.json
docs/src/components/MentionsSection/index.js
docs/src/data/features.js
docs/src/pages/index.js

- Add basic translations for Korean.
- Fix some broken links with i18n

Add basic translations for Korean

---

rio-backend/src/config/mod.rs

More `PathBuf`

---

docs/docusaurus.config.js
docs/i18n/pl/code.json
docs/i18n/pl/docusaurus-theme-classic/navbar.json

🇵🇱 Polish translation! 😊
Pretty muched cloned from https://github.com/raphamorim/rio/pull/368

feat(i18n): add polish translation to landing page

---

rio-backend/src/config/defaults.rs
rio-backend/src/config/keyboard.rs

fix: add default values to keyboard config

---

docs/docs/key-bindings.md

docs: mention that Ctrl + Shift + Tab moves to previous tab

---

docs/docs/configuration-file.md
docs/docs/features/color-automation-for-navigation.md
docs/docs/features/hyperlinks.md
docs/docs/features/iterm-image-protocol.md
docs/docs/features/spawn-or-fork.md
docs/docs/install/index.md
docs/docs/install/using-cargo.md
docs/docs/install/windows.md
docs/docs/navigation.md
docs/docs/plugins.md
rio-backend/src/config/defaults.rs

Cleaned up the documentation a bit.

docs: remove dead config options

---

sugarloaf/src/layout/span_style.rs
sugarloaf/src/sugarloaf/compositors/advanced.rs
sugarloaf/src/sugarloaf/primitives.rs

This makes `pub fn update_tree_with_new_line` a bit more readable in my opinion.

add From<&Sugar> for FragmentStyle

---

docs/docs/install/macos.md

https://ports.macports.org/port/rio/

docs: add MacPorts install info

---

CHANGELOG.md
corcovado/src/poll.rs
corcovado/src/stream.rs
corcovado/src/timer.rs
corcovado/test/test_custom_evented.rs
docs/blog/2023-07-07-release-0.0.7.mdx
docs/blog/2023-07-17-release-0.0.9.md
docs/blog/2023-08-02-release-0.0.15.mdx
docs/blog/2023-09-19-release-0.0.19.md
docs/blog/2024-04-18-looking-ahead-to-0.1.0.mdx
frontends/rioterm/src/bindings/bindings_wa/mod.rs
frontends/rioterm/src/bindings/bindings_winit/mod.rs
frontends/rioterm/src/router/window/mod.rs
frontends/rioterm/src/sequencer.rs
rio-backend/src/config/defaults.rs
rio-backend/src/config/mod.rs
rio-backend/src/crosswords/grid/mod.rs
sugarloaf/Cargo.toml
sugarloaf/README.md
sugarloaf/src/components/rich_text/image_cache/mod.rs
sugarloaf/src/components/rich_text/util/fxhash.rs
sugarloaf/src/components/text/glyph/brush.rs
sugarloaf/src/components/text/glyph/layout/builtin.rs
sugarloaf/src/components/text/glyph/layout/mod.rs
sugarloaf/src/components/text/mod.rs
teletypewriter/Cargo.toml
teletypewriter/README.md
wa/src/conf.rs
wa/src/event.rs
wa/src/native/macos.rs

Ran the repo through a couple spell checkers and fixed the user facing typos.

docs: fix user facing typos

---

README.md

The previous platform links are broken, directing you to Not Found pages. The Acknowledgments section was also broken due to a typo.
This PR aims to fix those issues.
_ps: you rock. cheers! 🖤_

fix: readme broken links

---

Cargo.toml
README.md
frontends/rioterm/src/screen/mod.rs
rio-proc-macros/Cargo.toml

Split support follow up

---

rio-backend/src/config/defaults.rs

Document font hinting in default toml config

---

docs/docs/install/linux.md

just linking to <https://aur.archlinux.org/packages/rio-git>

docs(installation): mention the AUR package

---

frontends/rioterm/src/context/mod.rs

... instead of waiting for two seconds to do so.

Update window title straight away

---

Cargo.lock
Cargo.toml

👋 seeing some version issue when doing the homebrew release build.
relates to https://github.com/Homebrew/homebrew-core/pull/198769
cc @raphamorim

fix: update version to 0.2.2 to match with the release

---

docs/docs/config/developer.md

hi, thanks for rio! This is just a tiny PR to add a note with possible log-level values to the docs

docs: note possible log-level values

---

frontends/rioterm/src/router/mod.rs

bugfix: fix duplicate tab_id by monotonic counter for unique tab IDs

---

docs/docs/releases.md
frontends/rioterm/src/application.rs
frontends/rioterm/src/context/mod.rs
frontends/rioterm/src/context/renderable.rs
frontends/rioterm/src/renderer/mod.rs
frontends/rioterm/src/screen/mod.rs
rio-backend/src/config/colors/term.rs
rio-backend/src/crosswords/mod.rs

Close https://github.com/raphamorim/rio/issues/945

Implement set_color and reset_color

---

.goreleaser.yaml

refactor(goreleaser): use conventional file names for deb, rpm

---

corcovado/src/sys/windows/from_raw_arc.rs
frontends/rioterm/src/context/title.rs
rio-backend/src/crosswords/mod.rs
rio-window/src/platform_impl/windows/dark_mode.rs
rio-window/src/platform_impl/windows/event_loop.rs
teletypewriter/src/windows/child.rs

feat: shell integration - current path

---

docs/blog/2025-03-01-rio-is-now-releasing-with-goreleaser.mdx

noticed instantly after you merged the previous pr :kek:

docs: update blog post

---

docs/docs/config.md

Improved clarity for Windows users.

Docs: Enhance Windows config path documentation

---

docs/docs/config.md

Remove $ extra in variable(sorry)

Docs: fix powershell variable

---

sugarloaf/src/components/rich_text/compositor.rs

fix line-height adds small gaps for box-drawing characters

---

docs/docs/escape-sequence-support.md
docs/docs/releases.md
rio-backend/src/crosswords/mod.rs
rio-backend/src/performer/handler.rs

add xtgettcap support

---

Cargo.lock
frontends/rioterm/src/router/window.rs
frontends/rioterm/src/screen/mod.rs
rio-backend/src/config/defaults.rs
rio-backend/src/config/mod.rs
rio-backend/src/config/window.rs
rio-window/Cargo.toml
rio-window/src/platform/macos.rs
rio-window/src/platform_impl/macos/window_delegate.rs
sugarloaf/src/context/mod.rs
sugarloaf/src/lib.rs
sugarloaf/src/sugarloaf.rs

Closes https://github.com/raphamorim/rio/issues/1097

implement p3 display for macos

---

frontends/rioterm/src/application.rs
frontends/rioterm/src/router/mod.rs
rio-backend/src/config/window.rs
rio-window/src/platform/x11.rs
rio-window/src/platform_impl/linux/mod.rs
rio-window/src/platform_impl/linux/wayland/event_loop/mod.rs
rio-window/src/platform_impl/linux/x11/activation.rs
rio-window/src/platform_impl/linux/x11/mod.rs
rio-window/src/platform_impl/linux/x11/monitor.rs
rio-window/src/platform_impl/linux/x11/util/randr.rs
rio-window/src/platform_impl/linux/x11/window.rs
rio-window/src/platform_impl/linux/x11/xdisplay.rs
teletypewriter/src/unix/mod.rs

There are just a lot of small things that clippy and rustc are complaining about right now, and this fixes them.

Apply fixes suggested by clippy
