Cargo.lock
Cargo.toml
rio/Cargo.toml
rio/src/screen/mod.rs
rio/src/sequencer.rs

This is probably related to #77. Looks like there is an additional parameter required to initialize the Clipboard with Wayland or any build with `--features=wayland` fails.
```shell
cargo build --release --features=wayland                                                                      
Compiling rio v0.0.6 (/home/bbx0/dev/repo/rio/rio)
error[E0061]: this function takes 1 argument but 0 arguments were supplied
--> rio/src/screen/mod.rs:67:25
|
67 |         let clipboard = Clipboard::new();
|                         ^^^^^^^^^^^^^^-- an argument of type `Option<*mut c_void>` is missing
|
note: associated function defined here
--> rio/src/clipboard.rs:34:19
|
34 |     pub unsafe fn new(display: Option<*mut c_void>) -> Self {
|                   ^^^ ----------------------------
help: …
```

Provide `display` to clipboard on wayland

---

docs/install/index.md

Setting "env-vars" doesn't work reliable in Windows environment, the new way works better.

Changes `env.vars` to `shell.program` on Win docs

---

config/src/defaults.rs
config/src/lib.rs
docs/docs/index.md
rio/src/screen/window/mod.rs
rio/src/sequencer.rs

This PR is an attempt to solve #143 
Allow setting the window height and width in the configuration file instead of hardcoded values. Fallback to 600x400 when not set. Tested in macos and KDE.

feat(config): add window-height and window-width parameters to config

---

CHANGELOG.md
rio/src/screen/constants.rs
rio/src/screen/window/mod.rs

Not sure how many apps integrate with this change, but at least tested that it enables Waybar on wayland to detect rio's desktop file and icon.

add application id to window on x11/wayland

---

docs/assets/styles-code.css

Right now it's inheriting from the reset, `Helvetica`, which makes a poor coding font 😄

Set font family of code blocks

---

CHANGELOG.md
docs/docs/key-bindings.md
rio/src/screen/bindings/mod.rs

Some of the original rio default keybinds for Linux & Windows were
conflicting with the default keybinds of the readline library, thereby
prohibiting the use of those readline keybinds in programs that make use
of readline (most shells, most REPLs, most editors)
This change updates the default modifiers in rio from just `CONTROL`
to `CONTROL` + `SHIFT` for those keybinds that would otherwise conflict
with the readline ones.
Also, the documentation for default Copy & Paste keybinds on Windows and
Linux has been corrected.

feat!: enable readline keybinds

---

docs/install/index.md

`rio` is now an official Arch Linux package: https://archlinux.org/packages/extra/x86_64/rio/

docs: update the link for Arch Linux package

---

Makefile

Updating the package name from rio to rioterm.

fix: change package name from rio to rioterm

---

docs/docs/configuration-file.md
rio-config/src/defaults.rs
rio-config/src/lib.rs
rio/src/screen/state.rs

Using the same color when selecting as the existing foreground color can be desired, since the color can include information about the text. 
This PR aims to add a configuration option for easily turning that feature on. By default the option is disabled. 
With the option set to false: 
With the option set to true: 
I apologize if this is not a desired feature, or if it already exists. I looked around the project but was unable to find anything about this.

feat: option for ignoring theme foreground selection color

---

.cargo/config.toml

See the comment for context, this should enable the compiler to produce better
code for ARM macs

refactor: enable CPU-specific optimizations on aarch64-apple-darwin

---

Cargo.toml

Instead of optimizing the release target for binary size (`s`), let's enable
full optimizations with `opt-level = 3`.

refactor: enable full optimizations for release profile

---

sugarloaf/Cargo.toml

Currently [`sugarloaf`] hasn't a `repository` url as you can see in the image:
this should be fixed with this PR.
[`sugarloaf`]: https://crates.io/crates/sugarloaf

sugarloaf: adding `repository` to `Cargo.toml`

---

docs/docs/documentation/configuration-file.md
rio-config/src/defaults.rs

Use the same style in the explanations inside the configuration sample.
Add missing `:` after `Example` and remove the indentation of the example itself so when uncommenting the example code is already usable.

docs: uniform style in configuration sample

---

docs/docusaurus.config.js

Small typo fix (21th -> 21st) in the website's tagline (unless that was intentional 🙂).

docs: fix typo in tagline

---

docs/docs/install/terminfo.md

The existing instructions assume, but don't state, that the rio repo has been cloned locally, and that the terminfo file is on disk.
This adds a note to clarify this requirement, and adds instructions on how to download the terminfo file, without cloning, and install it.

(docs)terminfo.md: add instructions to install when not cloned

---

frontends/multi/src/router/settings/mod.rs
frontends/multi/src/router/settings/screen.rs
frontends/multi/src/router/welcome.rs
rio-backend/src/config/mod.rs

Refactor some codes:
- Apply SSOT for config file path
It also includes bug fixes on Windows:
The welcome message now prints a valid path separator.
- Use `PathBuf` noramlly -> Reduce type conversions.
- Merge `welcome_content()` functions
If there's a refactoring you think is unnecessary, let me know and I'll remove it.

Some refactors

---

docs/docs/configuration-file.md
rio-backend/src/config/defaults.rs

Mention in the configuration docs that enabling/disabling background blur requires restarting Rio to take effect

docs(config): mention blur requires restart

---

docs/docusaurus.config.js
docs/i18n/es/code.json
docs/i18n/es/docusaurus-theme-classic/navbar.json

This PR adds the Spanish translation to the landing page :) 
There are still some texts that are not translated, like the footer and the page title; but this is common to the other translations (because these seem to be "hard coded"), so I figured that I should open the PR with what I have until we can translate the rest.

feat(i18n): add spanish translation to landing page

---

frontends/cross-winit/src/screen/bindings/mod.rs

The deleted keybindings were duplicates of https://github.com/raphamorim/rio/blob/208e913ed727c19e61847638f4ff226e37a0a189/frontends/cross-winit/src/screen/bindings/mod.rs#L742-L744 with the only difference between them being the spaces.
After deleting the lines I no longer had any issues with backspace deleting 2 characters when Kitty protocol is turned on (#344).
Before with Kitty `false`:
Before with Kitty `true`:
After with Kitty `false`:
After with Kitty `true`:

fix: remove duplicate kitty backspace keybinds

---

CHANGELOG.md
teletypewriter/src/unix/mod.rs

On Linux the program name ends with `\n` which breaks color automation.

fix: trim unix program name

---

frontends/cross-winit/src/screen/mod.rs
sugarloaf/src/layout/mod.rs

Currently the padding top is checked on startup, but not when the config is changed, which means going from `BottomTab` to `TopTab` will result in the navigation overlapping the first line (left @ f26f633):
`TopTab` to `BottomTab` results in a "wasted" line:
This should fix it :)

fix: update padding top on config change

---

frontends/cross-winit/src/screen/bindings/kitty_keyboard_protocol.rs
frontends/cross-winit/src/screen/context.rs
frontends/cross-winit/src/screen/mod.rs

I know it is pretty minor, but while jumping around in the code I noticed a few places cloning could be removed. 
Feel free to close the PR if I am mistaken, or there is a good reason for it :)

refactor(cross-winit): remove unnecessary cloning of key events

---

rio-backend/src/config/navigation.rs

Fixes the following compiler warnings that I got while building the latest version of `rio` for Arch Linux:
```
warning: `&` without an explicit lifetime name cannot be used here
--> rio-backend/src/config/navigation.rs:32:22
|
32 |     const PLAIN_STR: &str = "Plain";
|                      ^
|
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
= note: `#[warn(elided_lifetimes_in_associated_constant)]` on by default
help: use the `'static` lifetime
|
32 |     const PLAIN_STR: &'static str = "Plain";
|                       +++++++
warning: `&` without an explicit lifetime name cannot be used here
--> …
```

fix: use explicit lifetime for const str

---

docs/docs/configuration-file.md
rio-backend/src/config/defaults.rs

Reordering non-grouped keys to the top to prevent conflicts and unexpected scenarios.
Reason for this change:
In my OS (Arch Linux + Hyprland WM), the shell key is being merged with the [fonts] properties.
My config.toml:
```toml
[fonts]
family = "Maple Mono SC NF"
size = 20 
shell = { program = "/usr/bin/tmux", args = ["new-session", "-c", "/var/www"] }
```
As a result, an interpretation of how `rio-backend` sees the "fonts" group:
```json
{
"fonts": {
"family": "Maple Mono SC NF",
"size": 20,
"shell": {
"program": "/usr/bin/tmux",
"args": ["new-session", "-c", "/var/www"]
}
}
}
```
and shell is None because it was merged into fonts, disregarding my configuration.
My suggestion is to move up all keys that aren't grouped with brackets ([example]) to avoid merging and unexpected scenarios: …

docs: reordering keys to avoid conflicts

---

docs/docs/configuration-file.md
rio-backend/src/config/defaults.rs

`padding-x` was changed to 0 on all platforms in `v0.0.30`. 
[https://github.com/raphamorim/rio/blob/1fa31f7cf6caa1c0c4caf2a5268eb7cea8799d6a/rio-backend/src/config/defaults.rs#L6-L9](https://github.com/raphamorim/rio/blob/1fa31f7cf6caa1c0c4caf2a5268eb7cea8799d6a/rio-backend/src/config/defaults.rs#L6-L9)

docs: set padding-x default to 0

---

docs/docs/configuration-file.md
rio-backend/src/config/defaults.rs

`create_pty_with_fork` does not support starting in specific path (*yet?*).
[https://github.com/raphamorim/rio/blob/f4f8d6c381d905c7c108efacf6132ea0c9614aaf/teletypewriter/src/unix/mod.rs#L581](https://github.com/raphamorim/rio/blob/f4f8d6c381d905c7c108efacf6132ea0c9614aaf/teletypewriter/src/unix/mod.rs#L581)

docs: use-current-path requires use-fork to be false

---

flake.lock
flake.nix

This PR aims to make the current flake which was recently imported to use `flake-parts` to better handle nix systems using flake. Also, changes have been made to dependencies and the current flake lock as this PR brings additional inputs.
- Add flake-parts as input
- Add buildFeatures, buildNoDefaultFeatures
- Add logic `stdenv.*` for dependencies
- Add `gcc-unwrapped` as dependency
- Add ability to use `nix develop '.#stable'` and `nix develop '.#nightly'`
- Structure the flake according to flake-parts guides
- Inherit version from `Cargo.toml`
_(✅ indicates that the command output successfully)_
- `nix build` -  ✅ 
- `nix develop` - ✅ 
- `nix run` - ✅ 
- `nix develop ".#stable"` - ✅ 
- `nix develop ".#nightly"` - ✅

Flake: Cleanup and Refactoring

---

flake.nix
pkgRio.nix

Fixes the core dump when running `rio` with `nix`. @RaySlash you can take a look if you want.

flake: add `apps` entry and fix runtime error

---

frontends/rioterm/src/app/route.rs
frontends/rioterm/src/screen/mod.rs

Disables `blinking-cursor` when selecting text, since it results in the application scheduling a lot of “unnecessary” rerenders, as described in #437.
There is still a small delay on first selection render, but it is not noticeable after.
_With the change_:
[Screencast from 2024-01-30 00-20-41.webm](https://github.com/raphamorim/rio/assets/56034786/468338b2-fdf6-498e-af8b-8673dc2520e4)
_Without_:
[Screencast from 2024-01-28 23-59-41.webm](https://github.com/raphamorim/rio/assets/56034786/0ae43942-94db-4bbc-acd0-89df39990ee3)

refactor: disable cursor blink on selection (ref #437)

---

.envrc
pkgRio.nix

This fixes the build on Darwin by adding a dependency on MetalKit. I also did
some drive-by fixes of the `envrc` setup.
- **fix(envrc): reload when pkgRio.nix changes**
- **fix(envrc): evaluate the nix shellHook**
- **fix(pkgRio): add MetalKit for build on Darwin**

fix: build on Darwin

---

flake.nix

The Nix flake dev shell needs to pull conditionally loaded dynamic libraries such as `libxkbcommon` into scope manually because the `patch` step is missing when using `cargo` directly. The previous implementation of the dev shell includes the `buildInputs` into `LD_LIBRARY_PATH`, which are just the headers and not the dynamic libraries. This PR fixes that issue and makes the shell work on my machine :tm: .
c/o @TornaxO7 who recommended I open this PR.

Fix `LD_LIBRARY_PATH` in Nix flake dev shell

---

README.md

Very minor, so I ended up not even opening an issue for this, just a fix for installation links sending to old (invalid) ones.
**EDIT:** If it makes more sense, I can target this change to `0.x.x` branch instead.

Fix README.md installation links

---

pkgRio.nix

Reverts raphamorim/rio#516
Using nix to compile rio currently fails with `error: A hash was specified for dpi-0.1.1, but there is no corresponding git dependency.`
With this I'm successfully able to use `nix run`.

Revert "nix: add hash value for a dependency"

---

rio-backend/src/config/defaults.rs

I tried entering the URL in the default config, and it showed "Page not found"
I found the actual URL, and replaced it in `default.rs`: https://raphamorim.io/rio/docs/next/key-bindings#custom-key-bindings

Fixed custom key bindings URL in default config

---

CHANGELOG.md
docs/versioned_docs/version-0.0.x/command-line-interface.md
frontends/rioterm/src/cli.rs

refactor(cli): support a short variant (`-w`) for `--working-dir`

---

CHANGELOG.md
docs/versioned_docs/version-0.0.x/command-line-interface.md
frontends/rioterm/src/cli.rs
frontends/rioterm/src/main.rs
frontends/rioterm/src/router/mod.rs
rio-backend/src/config/mod.rs

closes #600
```bash
$ rio --write-config rio.toml
[INFO] rio_backend::config configuration file created rio.toml
$ rio --write-config
[INFO] rio_backend::config configuration path created /home/orhun/.config/rio
[INFO] rio_backend::config configuration file created /home/orhun/.config/rio/config.toml
```
Let me know if this needs any documentation update / other fixes :bear:

feat(config): support creating config via `--write-config`

---

docs/docs/changelog.md
rio-backend/src/config/defaults.rs
rio-backend/src/config/navigation.rs
rio-backend/src/config/renderer.rs
rio-backend/src/config/window.rs

let me know if this is yay or nay

feat(config): allow configuring with lowercase values for enums

---

docs/docs/changelog.md
docs/docs/config/mouse.md
rio-backend/src/config/defaults.rs
rio-backend/src/config/mod.rs

chore(config): rename option to hide-mouse-cursor-when-typing

---

docs/docs/features/vi-mode.md
rio-backend/src/config/defaults.rs

On the "bindings" section in default `config.toml`, it shows https://raphamorim.io/rio/docs/key-bindings#custom-key-bindings but this link is invalid now.
It seems https://raphamorim.io/rio/docs/config/bindings is correct, I think.

Fix invalid link in default config.toml

---

docs/docusaurus.config.js
docs/i18n/ja/code.json
docs/i18n/ja/docusaurus-theme-classic/navbar.json
docs/src/data/features.js

Added Japanese translation for landing page :)

[i18n] Japanese support for landing page

---

rio-backend/src/config/colors/mod.rs

- Fixed regex that checks hex size.
- Added a test case to verify conversion of RGBA hex colors (for example, `#15151580`).

Fix hex size validation and add test cases for RGBA hex conversion

---

rio-backend/src/config/defaults.rs

That fixes the broken settings window on Windows. Creating a new blank settings window that then launches a separate notepad window looks weird, but I don't think there's a better solution.
fix #677

fix: Set notepad as a default editor on windows

---

rio-backend/src/config/mod.rs

Fixes: https://github.com/raphamorim/rio/issues/801

Makes editor.args and shell.args optional in config.toml

---

docs/docs/command-line-interface.md
frontends/rioterm/src/cli.rs
frontends/rioterm/src/main.rs
frontends/rioterm/src/router/window.rs
rio-backend/src/config/window.rs

This PR adds support for specifying a custom window title using the --title argument in the CLI. This feature allows users to define a specific name for the window, improving usability in multi-window setups and enabling better integration with window managers.
closes #405

Allow Setting Window Title

---

docs/docs/config/padding.md
docs/docs/releases.md
rio-backend/src/config/defaults.rs

This little revision corrects the little helper text for the `padding-y` in the config. I was so confused!

fix y-axis hint in config and docs

---

docs/docs/config/editor.md

This PR addresses the discussion in https://github.com/raphamorim/rio/issues/832 by improving the documentation for the `editor` setting. It now mentions that the full path to the editor binary may be required in certain cases. Since I am unfamiliar with how Rio resolves binaries on Windows, the documentation changes are currently focused on Unix-like systems. Please feel free to expand or adjust it as needed!
As a side note, I think it's a good idea to keep that issue open if there are plans to revisit this behavior in the future. Many users likely expect that whatever is in their `PATH` should work seamlessly (at least, that’s my perspective).

Add warning about the editor path

---

docs/docs/releases.md
rio-backend/src/crosswords/mod.rs

This adds support for moving forward tabs in the grid using `CSI n I`. This sequence behaves like using tabs `\t` but also accepts a count argument to move multiple tabs forward.

add support for moving forward tabs

---

Cargo.lock
teletypewriter/Cargo.toml
teletypewriter/src/windows/child.rs
teletypewriter/src/windows/conpty.rs
teletypewriter/src/windows/pipes.rs

- Updates window.sys to version 0.58.
- A key change to this version is that the HANDLE type is now `*mut c_void`, so the code was changed to accomodate this.
- An important change is the manual implementation of the `Send` trait for `ChildExistWatcher`. The trait can no longer derived automatically because `*mut c_void` is not Send. However, pointers
are not Send more as a lint to developers (eg: a pointer to Rc<T>
would be safe), but `c_void` is Send and therefore it should be fine to derive it manually for the pointer.
See https://doc.rust-lang.org/nomicon/send-and-sync.html for details.

Update windows-sys crate version to 0.59

---

frontends/rioterm/src/application.rs
frontends/rioterm/src/context/mod.rs

Am I missing something? 👁️ 👁️ 
Its wayyyyyyyyyyyyyyyyyyyy smoother now
Left: Latest nightly release
Right: This PR
https://github.com/user-attachments/assets/6d325deb-219a-45ec-aacc-518cb64197b2

feat: Sync text selection to available frames instead of 60ms

---

Cargo.toml
frontends/rioterm/Cargo.toml

Fixes the empty readme on crates.io 😄

fix(rioterm): inherit workspace readme for crate

---

.github/workflows/release.yml

fix: Relax libc requirements on ubuntu by compiling Rio in a 22.04 runner instead of 24.04

---

docs/docs/releases.md
frontends/rioterm/src/router/mod.rs
frontends/rioterm/src/router/routes/assistant.rs

- No more need to press **twice** the Enter key in `ConfirmQuit`, `Welcome` or `Assistant` routes.
- Writing (and therefore pasting) was allowed while rendering the `Assistant` route. You could run stuff by pasting scripts with breaklines without the need to go to the terminal route
LMK if I broke something but from my own tests all went just fine

fix: Better handling of Escape and Enter keys

---

docs/docs/config.md
rio-backend/src/config/defaults.rs

Default font style values is writtend as 'normal' and 'italic' both throw an error because is expect that styles to be "Normal" and "Italic"
*Capitalize font style values in the docs and in `rio-backend/src/config/defaults.rs` 
- Change "normal" to "Normal"
- Change "italic" to "Italic"

update default font style from normal to Normal

---

rio-backend/src/config/defaults.rs

I noticed that the link below is deprecated, as it results in a "not found" page:
https://github.com/raphamorim/rio/blob/9bfd12dff3dd69f72c6c3e7db0d48717259e9890/rio-backend/src/config/defaults.rs#L459
This PR is to update this link.

Update broken link on generated config.toml

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml

@raphamorim you'll need to set 2 more secrets:
```sh
gh secret set KEYCHAIN_PASSWORD --body "some password to lock and unlock the keychain"
gh secret set MACOS_NOTARY_KEYCHAIN_PROFILE --body "a profile name"
```
this uses the recently added native notarization: https://goreleaser.com/customization/notarize/#application-bundles-and-dmgs

ci: native macos notarization

---

.goreleaser.yaml

available in the nightly goreleaser build building rn

fix(goreleaser): do not run after hooks on intermediary steps

---

docs/blog/2025-03-01-rio-is-now-releasing-with-goreleaser.mdx

- some wording changes (IMHO reads a bit better)
- some typos

docs: update blog post

---

docs/docs/key-bindings.md
frontends/rioterm/src/bindings/mod.rs
frontends/rioterm/src/context/grid.rs
frontends/rioterm/src/context/mod.rs
frontends/rioterm/src/screen/mod.rs

This PR add two new commands
```rust
/// Select next split if available if not next tab
SelectNextSplitOrTab,
/// Select previous split if available if not previous tab
SelectPrevSplitOrTab,
```
This allows to switch between splits and tabs with single key binding.
I understand if you dont want to merge this and leave it for the plugin system, when available.
Thanks for making this great software.

Add Switch to Next/Prev Split or Tab command

---

misc/osx/Rio.app/Contents/Info.plist

Made changes that now allows Rio to be used to execute unix executables, not just trying to open them in an editor.
(Edit, oh yeah and added terminal as a keyword for the app so in shows up in spotlight when searching terminal)
(This may or may not work, I didn't bother to try, just yoinked the idea from an another terminal.)
There's also other goodies in there, if you want you can throw this one into the can and do a bigger refactor :)

Small changes to macOS info.plist file

---

frontends/rioterm/LICENSE
frontends/wasm/LICENSE
rio-backend/LICENSE
rio-proc-macros/LICENSE
rio-window/LICENSE
teletypewriter/LICENSE
wa/LICENSE

In the case of crates published on crates.io, like `rioterm`, `rio-proc-macros`, `teletypewriter`, etc., this fixes missing license text in the published crates. Normally, I would just use symbolic links to the top-level `LICENSE` file in a PR like this, but I followed the lead of existing license files like `corcovado/LICENSE` and made copies instead.
I also added the `LICENSE` file to `frontends/wasm`. It isn’t published on crates.io, and I don’t entirely understand how to use it, but I assumed it was the right thing to do there as well.
Including the license text with published crates is necessary so that people can comply with the chosen `MIT` license, which says:
https://github.com/raphamorim/rio/blob/73f0158330a0fe6d639406fe748588dc1bb69816/LICENSE#L12-L13

Add missing LICENSE files to several workspace crates

---

docs/docs/config.md
docs/docs/releases.md
frontends/rioterm/src/context/grid.rs
rio-backend/src/config/defaults.rs
rio-backend/src/config/mod.rs
sugarloaf/src/font/fonts.rs
sugarloaf/src/font/mod.rs

Fixes https://github.com/raphamorim/rio/issues/124
```toml
fonts.symbol-map = [{ start = "2297", end = "2299", font-family = "Cascadia Code NF" }]
```

feat: symbol-map

---

docs/docs/default-colors.md

Remove duplicate key `cursor` in table `colors`, which throws when pasted into the configuration.

Remove duplicate cursor in default-colors.md

---

docs/docs/config.md
docs/docs/releases.md
rio-backend/src/config/defaults.rs
rio-backend/src/config/mod.rs

Uses `$XDG_CONFIG_HOME` to find configuration files on Linux, with a lower priority than `$RIO_CONFIG_HOME` but higher than `$HOME` as specified in [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/)
> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable `$XDG_CONFIG_HOME`.
The fallback to `$HOME/.config` is specified further below:
> `$XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.
Previous work at #14 and also needed for flathub/flathub#6483

Read configuration from $XDG_CONFIG_HOME on Linux

---

docs/docs/install/using-cargo.md

without `--locked` its borken because cargo install doesnt respect the lock file without it

Better lock that cargo install

---

docs/docs/releases.md
teletypewriter/src/unix/mod.rs

When passing `std::env::vars_os()` to the spawned shell inside a Flatpak sandbox, it ends up overriding important host environment variables with overridden values meant for the sandboxed application (in this case, Rio). Most notably, `$XDG_CONFIG_HOME` is overridden by the value passed to Rio, which is `$HOME/.var/app/com.rioterm.Rio/config` instead of `$HOME/.config` (or whatever value the user has set):
(current behavior)
There's no need to pass any environment variables to the shell outside the sandbox, they get inherited from the process that spawned the Flatpak sandbox, which is usually the user session that already has the environment properly set up:
(fixed behavior)
Additionally, the order of the parameters does not matter in this scenario, so I moved setting `TERM_PROGRAM` (now …

Skip passing sandbox env to spawned shell in Flatpak

---

misc/com.rioterm.Rio.metainfo.xml

Branding colors are used by appstream-based stores (such as Flathub) to generate cards for the app. Flathub suggests we add a dark and a light branding color. It should be colorful, have good contrast with the icon but still make sense.
The dark color was suggested by ChatGPT 😆 but it's vivid and I believe it fits well. The light color was obtained by lightening the dark color until it has good enough contrast with the foreground text, ensuring it is accessible. Preview:

Add branding colors to metainfo

---

docs/docs/config.md

This section of the docs had some ambiguous English, I thought I'd help clear it up:

disambiguate english in config docs

---

docs/docs/install/linux.md

I hope this is formatted alright? I wasn't sure if I should make an issue or a PR to mention the terminal is available in the Terra repository. I'm using it from there right now. =]

docs: Mention Terra package for Fedora users

---

flake.nix

You don't need a custom `rust-toolchain` if you aren't actually adding any extensions that aren't already present.
- For the `devShells.*.msrv` output, it was never using the project's `rust-toolchain.toml` (that is, assuming you use it for the MSRV toolchain). Now it is.
- For the `packages.*.rio` output, you can just use `rust-bin.stable.latest.minimal`. That's all that is required to build with `rustPlatform.buildRustPackage`.

flake: devShells+packages: fix rust-overlay toolchain usage

---

docs/docs/releases.md
sugarloaf/src/components/rich_text/mod.rs
sugarloaf/src/font/cjk_metrics_tests.rs
sugarloaf/src/font/metrics.rs
sugarloaf/src/font/mod.rs
sugarloaf/src/layout/content.rs

This commit implements a comprehensive solution for CJK font metrics issues by adopting an approach where the primary font determines cell dimensions for ALL fonts, ensuring consistent terminal grid alignment.
Key changes:
- Add new font/metrics.rs with Metrics and FaceMetrics structs
- Implement calc() and calc_with_primary_cell_dimensions() methods
- Add primary metrics caching in FontLibraryData for performance
- Ensure consistent cell dimensions across Latin and CJK fonts
- Maintain font-specific positioning (underline, strikethrough) details
- Add comprehensive unit tests (30 tests) covering all font combinations
- Test realistic scenarios with Cascadia Code, Noto CJK, Source Han Sans
- Verify baseline consistency, rich text format, and edge cases
The implementation ensures that:
- …

Implement consistent font metrics for CJK rendering

---

.github/workflows/test.yml
Cargo.lock
docs/docs/config.md
docs/docs/install/build-from-source.md
docs/docs/install/linux.md
frontends/rioterm/Cargo.toml
frontends/rioterm/src/application.rs
frontends/rioterm/src/constants.rs
frontends/rioterm/src/renderer/mod.rs
rio-backend/src/config/bell.rs
rio-backend/src/config/mod.rs
rio-backend/src/crosswords/mod.rs
sugarloaf/src/components/quad/mod.rs
sugarloaf/src/sugarloaf.rs
sugarloaf/src/sugarloaf/state.rs

This pull request adds support for a visual bell feature in the terminal, allowing the screen to briefly flash when a bell event occurs (if enabled in configuration). 
* Added a new `Bell` configuration struct to `Config`, with a default value and deserialization support, allowing users to enable or disable the visual bell (`rio-backend/src/config/mod.rs`). [[1]](diffhunk://#diff-0c221060fd80a6b14b9208f6415aca6bdf0b24afd4b27e9078f663dcb813aa7fR1) [[2]](diffhunk://#diff-0c221060fd80a6b14b9208f6415aca6bdf0b24afd4b27e9078f663dcb813aa7fR14) [[3]](diffhunk://#diff-0c221060fd80a6b14b9208f6415aca6bdf0b24afd4b27e9078f663dcb813aa7fR168-R169) [[4]](diffhunk://#diff-0c221060fd80a6b14b9208f6415aca6bdf0b24afd4b27e9078f663dcb813aa7fR540)
* In the frontend application event handler, added logic to check …

Add audible & visual bell support

---

.goreleaser.yaml
docs/docs/frequently-asked-questions/index.md
docs/docs/install/index.md
docs/docs/install/linux.md
docs/docs/install/terminfo.md
docs/docs/releases.md

Closes #1264
Users on Debian 13+ and Ubuntu 24.04+ are experiencing installation failures when trying to install Rio's `.deb` packages. The error occurs because these distributions now include Rio's terminfo in the `ncurses-term` package (version 6.5+), causing a file conflict:
```
dpkg: error processing archive /home/Data/Downloads/rioterm_0.2.28_amd64_x11.deb (--unpack):
trying to overwrite '/usr/share/terminfo/r/rio', which is also in package ncurses-term (6.5+20250216-2)
```
1. **For Debian packages**:
- Removed the terminfo file from the package contents completely
- The terminfo is now provided by the system's ncurses-term package on Debian 13+/Ubuntu 24.04+
- For older systems (like Ubuntu 22.04 with ncurses-term 6.3), users can manually install the terminfo
2. **For RPM …

fix debian conflicts with ncurses-term
